# Generated by Django 2.0.3 on 2018-03-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
