# Generated by Django 2.0.3 on 2018-03-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_models', '0004_auto_20180331_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
